name: Integration Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
      runs-on: ubuntu-latest
      outputs:
        tests: ${{ steps['set-tests'].outputs['tests'] }}
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 2
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 7

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'pnpm'

        - name: Install dependencies
          run: pnpm install

        - id: set-tests
          name: Set Tests
          run: echo "::set-output name=tests::$(npx jest --listTests --json)"
  build:
      name: Build and Test
      needs:
        - setup
      strategy:
        matrix:
          test: ${{ fromJson(needs.setup.outputs['tests']) }}
      timeout-minutes: 15
      runs-on: ubuntu-latest
      # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      permissions:
        id-token: write
        contents: read

      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 7

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'pnpm'

        - name: Install dependencies
          run: pnpm install

        - name: Configure AWS credentials from Test account
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-session-name: aws-cdk-scratchpad-tests
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Test
          run: npx jest ${{ matrix.test }}